class B 
{
	public static void main(String[] args) 
	{
		System.out.println("main begin");
		try
		{
			
		}
		catch (ArithmeticException )
		{
		}
		System.out.println("main end");
	}
}


/* even though the try catch is epty but it gives exception  and 
As the catch is unchecked gives error without creating the object or identifier*/

